### ISSUE TITLE
"Failed to generate hash: a file could not be accessed." Not fixed by Admin rights

### ISSUE THREAD

**Issue by dreimer1986** [StarGazer1258/BeatDrop#45]
New Steam version of Beat Saber on a Steam Library on drive F. Songs converted to new format by SongCore Addin. Songs work ingame. I tried a complete reset of appdata folders and added the Beat Saber path again. Result: 
![image](https://user-images.githubusercontent.com/29841368/59564469-95b11900-9047-11e9-81f8-a05f2072405e.png)

Only log I found was in C:\Users\USERNAME\AppData\Roaming\beatdrop\Local Storage\leveldb
https://hastebin.com/xafesebefu.cpp

**Comment by FolkSong** [comment]
Same problem here after updating to latest beta.

**Comment by dreimer1986** [comment]
2.5.2 final. Same issue, application not useable at all. Back to ModAssistant for now...

**Comment by StarGazer1258** [comment]
A patch for this is coming VERY soon. Please be patient as we try to fix this.

**Comment by dreimer1986** [comment]
WOW! That was fast. Thx ^^

**Comment by StarGazer1258** [comment]
Fixed in 57c650dabf395da68e5ee7edd35429861bcca6b0. Will be pushed to stable in a few days. Thanks for waiting. :)

**Comment by xbkingx** [comment]
Still happening in 2.5.4 beta, so still an active issue.

Also, seems weird that a higher version beta (2.5.4) would give an update notification and install a lower version stable (2.5.2) over itself. It's just asking for configuration problems.

**Comment by StarGazer1258** [comment]
This shouldn't be possible, as this error message was revised. What exactly is happening?

**Comment by StarGazer1258** [comment]
I looked back through the code and found a small bug that may have a similar issue for maps with more than one set. Please try 2.5.5-beta and let me know if you have any further issues.

**Comment by xbkingx** [comment]
I fixed it by manually deleting the `C:\Users\(username)\AppData\Roaming\BeatDrop` folder. I have 800+ songs, so in 2.5.2 there would be (I assume) hundreds of error messages to dismiss. After wiping and installing 2.5.4 beta, only 5-6 error messages (they don't continue off screen).

The previous stable release also choked on my library at every launch, but the single error was dismissable. I think it just got stuck on the Scanning for songs overlap.

Not sure what the log file encoding is, so I just did a quick and dirty conversion to UTF-8 and deleted every other character to see if I could spot anything. Some of this probably the conversion.

It's possible that selecting to not delete old versions of maps is part of the problem.

`\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\1962-1365UptownFunk\\\\info.dat\"},{\"hash\":\"d110e413fb7fb462b692f1f17b835cf8b7280884\",`

`\"file\":•K«ðù\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\1962-20536UptownFunk\\\\info.dat\"},{\"hash\":\"0f35805077a081d4e15b4a71147552aca93b88e8\",`

Other oddities:

Custom levels path weirdness...
`\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\17465-18997Animals(Radioedit)\\\\info.dat\"},{\"hash\":\"376abe290620e443e9451366accb30e5095edbce\",\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\17466-18998Backbone\\\\info.dat\"},{\"hash\":\"695455f934af00bb25cbd94c31c4aa1f273879ab\",\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\Curçâ¢ùstomLevels\\\\17467-18999Blah!!-HiTECHNINJA\\\\info.dat\"},{\"hash\":\"7690e21427b432794fe11d4a9a13c577d420858b\",\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\17468-19024BootyBounce-Tujamo&TaioCruz\\\\info.dat\"},{\"hash\":\"2c16c3f445ffd35067f76762890b72b3ef9b8352\",\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\17470-19002Dancin(KronoRemix)\\\\info.dat\"},{\"hash\":\"320d2934280c621ba3f1c13c5a4c2e2c6fe33b89\",\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\17471-19003FaceMyFears\\\\info.dat\"},{\"hash\":\"440945a4fe86b5e3ee7f03b98c636c881930072f\",`

`\"file\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\1121-766Vicetone-WayBackft.CoziZuehlsdorff\\\\info.dat\"},{\"hash\":\"a4887df9b155fce514e7fc8fbc9bd61de613920d\",\"+[ùfile\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\\\\BeatSaber_Data\\\\CustomLevels\\\\11267-11952YouTubeRewind\\\\info.dat\"},{\"hash\":\"5eec215fec16233dd54ca531fb91c20a7b79662c\",`


Not sure if it helps, but I downloaded a song (no problems) and pulled the log file. Here's the top section of the log: 
`(HUkùMETA:file://
˜‚ó¤¥Ìº–¸_file://persist:root‰¸{"songs":"{\"songs\":[{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":false,\"hard\":false,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"Believer\",\"songSubName\":\"ImagineDragons\",\"songAuthorName\":\"Rustic\",\"levelAuthorName\":\"rustic\",\"bpm\":125},\"stats\":{\"downloads\":495447,\"plays\":70725,\"downVotes\":12,\"upVotes\":741,\"heat\":17.8181942,\"rating\":0.9181877068246497},\"description\":\"Currentlyexpertonly.Eventsincluded.\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc60e9\",\"key\":\"b\",\"name\":\"ImagineDragons-Believer\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84e8c4\",\"username\":\"rustic\"},\"uploaded\":\"2018-05-08T18:56:36.000Z\",\"hash\":\"19f2879d11a91b51a5c090d63471c3e8d9b7aee3\",\"downloadURL\":\"/api/download/key/b\",\"coverURL\":\"/cdn/b/19f2879d11a91b51a5c090d63471c3e8d9b7aee3.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":false,\"hard\":true,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"HarderBetterFasterStronger\",\"songSubName\":\"DaftPunk\",\"songAuthorName\":\"RunRockGame\",\"levelAuthorName\":\"runrockgame\",\"bpm\":123},\"stats\":{\"downloads\":437041,\"plays\":74223,\"downVotes\":241,\"upVotes\":3027,\"heat\":64.4073144,\"rating\":0.8889532219004831},\"description\":\"Expert&Hard|600+Blocks|FullSong3:44|IncludesLighting.Requestto:@themakertales\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc63dd\",\"key\":\"32e\",\"name\":\"DaftPunk-HarderBetterFasterStronger\",\"uploader\":{\"_id\":\"5cff0b7398cc5a672c84f04e\",\"username\":\"runrockgame\"},\"uploaded\":\"2018-06-01T18:01:45.000Z\",\"hash\":\"7c7f38d467bb43fe11a142581e63e324622ecc71\",\"downloadURL\":\"/api/download/key/32e\",\"coverURL\":\"/cdn/32e/7c7f38d467bb43fe11a142581e63e324622ecc71.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":true,\"hard\":true,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"GangnamStyle\",\"songSubName\":\"PSY\",\"songAuthorName\":\"GreatYazer\",\"levelAuthorName\":\"greatyazer\",\"bpm\":132},\"stats\":{\"downloads\":410367,\"plays\":82700,\"downVotes\":174,\"upVotes\":3673,\"heat\":40.8226551,\"rating\":0.9168796138737239},\"description\":\"Expert,Hard,andNormaltracks.Itriedmybesttosetupthechoruschartstoallowyoutomimictheclassicdancemoves.Ithinkitmatchesupquitenicely.IhopeyouhaveasmuchfunplayingasIdidmakingthis!Enjoy!\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc620d\",\"key\":\"141\",\"name\":\"GANGNAMSTYLE\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84ea71\",\"username\":\"greatyazer\"},\"uploaded\":\"2018-05-20T09:59:02.000Z\",\"hash\":\"8e7e553099436af31564adf1977a5ec42a61cfff\",\"downloadURL\":\"/api/download/key/141\",\"coverURL\":\"/cdn/141/8e7e553099436af31564adf1977a5ec42a61cfff.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":true,\"normal\":true,\"hard\":true,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"Beatit\",\"songSubName\":\"MichaelJackson\",\"songAuthorName\":\"Freeek\",\"levelAuthorName\":\"freeek\",\"bpm\":139},\"stats\":{\"downloads\":408423,\"plays\":117624,\"downVotes\":208,\"upVotes\":2716,\"heat\":50.6264164,\"rating\":0.8900573687599906},\"description\":\"Easy/Normal/Hard/Expert-Obstaclesandminespurelyfordancemoves!100%ExpertPlaythrough:https://bit.ly/2IKzCp3\\r\\n\\r\\n-Freeek=)\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc62d6\",\"key\":\"217\",\"name\":\"Beatit-MichaelJackson\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84e8ad\",\"username\":\"freeek\"},\"uploaded\":\"2018-05-25T14:20:19.000Z\",\"hash\":\"4b2da842b687ec4cfbc948c583c21c79d4120de0\",\"downloadURL\":\"/api/download/key/217\",\"coverURL\":\"/cdn/217/4b2da842b687ec4cfbc948c583c21c79d4120de0.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":false,\"hard\":false,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"TakeOnMe\",\"songSubName\":\"\",\"songAuthorName\":\"a-ha\",\"levelAuthorName\":\"jackscape\",\"bpm\":168},\"stats\":{\"downloads\":393297,\"plays\":36801,\"downVotes\":142,\"upVotes\":1597,\"heat\":18.0219074,\"rating\":0.8740818905020186},\"description\":\"Expertonly\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc60e7\",\"key\":\"9\",\"name\":\"a-ha-TakeOnMe\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84e8bb\",\"username\":\"jackscape\"},\"uploaded\":\"2018-05-08T17:44:17.000Z\",\"hash\":\"2aa1f5192828e075c30dd015b1e132bba912eb86\",\"downloadURL\":\"/api/download/key/9\",\"coverURL\":\"/cdn/9/2aa1f5192828e075c30dd015b1e132bba912eb86.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":true,\"hard\":true,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"Africa\",\"songSubName\":\"\",\"songAuthorName\":\"Toto\",\"levelAuthorName\":\"calijor\",\"bpm\":92},\"stats\":{\"downloads\":365784,\"plays\":27043,\"downVotes\":423,\"upVotes\":1309,\"heat\":39.6558782,\"rating\":0.7286792231962599},\"description\":\"Blesstherains!\\r\\n\\r\\nExpert,hard,andnormaldifficultyavailable.Idoapologize,butIthinkthey'reabitharderthanvanilla.\\r\\n\\r\\nBPM:92\\r\\nNotes:883(expert)\\r\\nDuration:4:20\\r\\n\\r\\nPreview:https://youtu.be/SLpUwKson80\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc6203\",\"key\":\"137\",\"name\":\"Toto-Africa\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84ebb1\",\"username\":\"calijor\"},\"uploaded\":\"2018-05-20T02:51:20.000Z\",\"hash\":\"12fee98db7d2080724435d0a1442545f21a9134d\",\"downloadURL\":\"/api/download/key/137\",\"coverURL\":\"/cdn/137/12fee98db7d2080724435d0a1442545f21a9134d.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":false,\"hard\":true,\"expert\":false,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"FeelGoodInc.\",\"songSubName\":\"\",\"songAuthorName\":\"Gorillaz\",\"levelAuthorName\":\"gavinmac\",\"bpm\":139},\"stats\":{\"downloads\":322662,\"plays\":31080,\"downVotes\":349,\"upVotes\":759,\"heat\":46.4618283,\"rating\":0.6625999728181062},\"description\":\"Hardmodeonly,Morecominginthefuture.\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc62a0\",\"key\":\"1de\",\"name\":\"FeelGoodInc.-TheGorillaz\",\"uploader\":{\"_id\":\"5cff0b7398cc5a672c84ed67\",\"username\":\"gavinmac\"},\"uploaded\":\"2018-05-23T20:06:47.000Z\",\"hash\":\"834bb9533ea0ba5dec806461230e103b85e1a5e3\",\"downloadURL\":\"/api/download/key/1de\",\"coverURL\":\"/cdn/1de/834bb9533ea0ba5dec806461230e103b85e1a5e3.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":false,\"hard\":true,\"expert\":false,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"Rasputin(FunkOverload)\",\"songSubName\":\"\",\"songAuthorName\":\"Jobas\",\"levelAuthorName\":\"jobas\",\"bpm\":149},\"stats\":{\"downloads\":322526,\"plays\":29624,\"downVotes\":225,\"upVotes\":3732,\"heat\":39.4336913,\"rating\":0.9065294268342207},\"description\":\"Hard\\r\\nBpm147\\r\\nspeedupversionofrasputinOriginal\",\"deletedAt\":null,\"_id\":\"5cff620c48229f7d88fc61f0\",\"key\":\"124\",\"name\":\"Rasputin(FunkOverload)\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84e9a2\",\"username\":\"jobas\"},\"uploaded\":\"2018-05-19T16:36:34.000Z\",\"hash\":\"9a1d001995cc0a2014352aa7148cbcbf2e489d89\",\"downloadURL\":\"/api/download/key/124\",\"coverURL\":\"/cdn/124/9a1d001995cc0a2014352aa7148cbcbf2e489d89.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":true,\"normal\":false,\"hard\":true,\"expert\":true,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"BohemianRhapsody\",\"songSubName\":\"Queen\",\"songAuthorName\":\"KingPeucheYouTube\",\"levelAuthorName\":\"kingpeuche\",\"bpm\":120},\"stats\":{\"downloads\":306550,\"plays\":21844,\"downVotes\":259,\"upVotes\":1294,\"heat\":81.5434737,\"rating\":0.796749240927648},\"description\":\"Gentlemen,IpresenttoyouBohemianRhapsodybyQueen.\\r\\n\\r\\nDuration:5:56\\r\\nNotes:991\\r\\nVeryVeryFrighteningLightning:Included\\r\\n\\r\\n-Expert\\r\\n-Hard\\r\\n-Easy\\r\\n\\r\\nNowIknowwhatyou'rethinking,\\\"Whyhasn'tanybodydonethisyet!?\\\".\\r\\nWelltherearetwoprimaryreasons,thefirstbeingtheLoudnesswar(Googlethat)hascausedalloriginalBohemianRhapsodyfilesonlinetobeabsurdlyquiet.ThesecondbeingthattheEditordoesnotfunctionideallywithsongsthathavemultipleBPMs.\\r\\n\\r\\nDidIedittheaudiotomakeitpossibletobeheardthroughthesaberslashes?Yes.\\r\\nDidIhavetogothroughthisentireprocessandputthenotesinbyearratherthanwithBeatSnapping?Alsoyes.\\r\\n\\r\\nDidIdoitforyou,theplayer,tobeabletoenjoyBeatSabertoperhapsthegreatestsongofalltime?HellyesIdid,andIdiditbecausetheworlddeservestofinallyseethisdamnedmasterpieceinthegame.\\r\\n\\r\\n\\r\\nFeelfreetoleaveyourexperiencesandfeedbackbelow.Anycomment,goodorbad,meanstheworldtome.\\r\\n\\r\\nAlso,findmeonYouTubeifyou'dliketobenotifiedofwhenImakeanewsong.\\r\\nhttps://www.youtube.com/user/1peewerking1\\r\\n\\r\\nEnjoyyourself.\",\"deletedAt\":null,\"_id\":\"5cff620d48229f7d88fc6541\",\"key\":\"4a6\",\"name\":\"BohemianRhapsody-Queen\",\"uploader\":{\"_id\":\"5cff0b7398cc5a672c84ef92\",\"username\":\"kingpeuche\"},\"uploaded\":\"2018-06-10T21:36:24.000Z\",\"hash\":\"9a8b9b0ecc22de615cd99454579b6aac685f4b1c\",\"downloadURL\":\"/api/download/key/4a6\",\"coverURL\":\"/cdn/4a6/9a8b9b0ecc22de615cd99454579b6aac685f4b1c.jpg\"},{\"metadata\":{\"difficulties\":{\"easy\":false,\"normal\":true,\"hard\":true,\"expert\":false,\"expertPlus\":false},\"characteristics\":[],\"songName\":\"SevenNationArmy\",\"songSubName\":\"TheWhiteStripes\",\"songAuthorName\":\"BlueASIS\",\"levelAuthorName\":\"blueasis\",\"bpm\":124},\"stats\":{\"downloads\":301080,\"plays\":56470,\"downVotes\":103,\"upVotes\":2265,\"heat\":73.9629224,\"rating\":0.9124885826845968},\"description\":\"UPDATED!@BlueASIS#4095onDiscordletmeknowwhatyouthink\",\"deletedAt\":null,\"_id\":\"5cff620d48229f7d88fc64a0\",\"key\":\"3fc\",\"name\":\"TheWhiteStripes-SevenNationArmy\",\"uploader\":{\"_id\":\"5cff0b7298cc5a672c84eb5d\",\"username\":\"blueasis\"},\"uploaded\":\"2018-06-06T18:51:03.000Z\",\"hash\":\"0b0ad0f34b2d0687a9794bcf5019100fda06971e\",\"downloadURL\":\"/api/download/key/3fc\",\"coverURL\":\"/cdn/3fc/0b0ad0f34b2d0687a9794bcf5019100fda06971e.jpg\"}],\"downloadingCount\":0,\"waitingToDownload\":[],\"downloadedSongs\":[{\"hash\":\"edf637f016aafd091b9b1ace8a0f093fc137b0ff\",`

And the bottom...
`\"discoveredFiles\":13039,\"processedFiles\":13039,\"scanningForSongs\":false,\"scrollTop\":0}","mods":"{\"mods\":[],\"modDetails\":{},\"installedMods\":[{\"id\":\"5cfe578d0a8c00640fb97091\",\"name\":\"BeatSaberTweaks\",\"version\":\"4.4.4\",\"files\":[\"Plugins/BeatSaberTweaks.dll\"],\"dependsOn\":[\"CustomUI\",\"Harmony\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d02749c7661221f0c4f097c\",\"name\":\"BSUtils\",\"version\":\"1.3.6\",\"files\":[\"Plugins/BS_Utils.dll\"],\"dependsOn\":[\"IniParser\"],\"active\":true,\"dependencyOf\":[\"CustomColors\",\"BeatSaverDownloader\",\"CustomPlatforms\",\"CustomSabers\",\"IntroSkip\",\"ParticleOverdrive\",\"PracticePlugin\",\"CustomNotes\",\"Counters+\",\"YURFitCalorieTracker\",\"SongCore\"]},{\"id\":\"5d03fe257661221f0c4f09b3\",\"name\":\"CustomUI\",\"version\":\"1.5.11\",\"files\":[\"Plugins/BeatSaberCustomUI.dll\"],\"dependsOn\":[\"Harmony\"],\"active\":true,\"dependencyOf\":[\"CustomColors\",\"BeatSaverDownloader\",\"CustomAvatars\",\"CustomPlatforms\",\"CustomSabers\",\"IntroSkip\",\"ParticleOverdrive\",\"PerfectionDisplay\",\"PracticePlugin\",\"CustomNotes\",\"Counters+\",\"SongRefreshButton\",\"YURFitCalorieTracker\",\"SongCore\",\"BSIPAModList\"]},{\"id\":\"5cfe55590a8c00640fb9706f\",\"name\":\"CustomColors\",\"version\":\"1.15.1\",\"files\":[\"Plugins/CustomColors.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d0811fbed00193b6ebbab8a\",\"name\":\"BeatSaverDownloader\",\"version\":\"4.2.1\",\"files\":[\"Plugins/BeatSaverDownloader.dll\"],\"dependsOn\":[\"SongCore\",\"BSUtils\",\"Harmony\",\"CustomUI\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[\"\"]},{\"id\":\"5cff3c907661221f0c4f08ec\",\"name\":\"CustomAvatars\",\"version\":\"4.7.3\",\"files\":[\"CustomAvatars/NoAvatar.avatar\",\"CustomAvatars/OokaMiko.avatar\",\"CustomAvatars/Shaders/customavatars.assetbundle\",\"CustomAvatars/Template.avatar\",\"CustomAvatars/TemplateFullBody.avatar\",\"Plugins/CustomAvatar.dll\"],\"dependsOn\":[\"CustomUI\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe57080a8c00640fb97088\",\"name\":\"CustomPlatforms\",\"version\":\"2.8.2\",\"files\":[\"CustomPlatforms/LightDisc.plat\",\"CustomPlatforms/Pulse.plat\",\"CustomPlatforms/Technology.plat\",\"Plugins/CustomPlatforms.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe575e0a8c00640fb9708e\",\"name\":\"CustomSabers\",\"version\":\"2.9.1\",\"files\":[\"CustomSabers/NeoKatanas.saber\",\"CustomSabers/Oldschool_Default.saber\",\"CustomSabers/Plasma_Katana.saber\",\"Plugins/CustomSaber.dll\"],\"dependsOn\":[\"CustomUI\",\"Harmony\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe56770a8c00640fb97081\",\"name\":\"IntroSkip\",\"version\":\"2.2.4\",\"files\":[\"Plugins/IntroSkip.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d016e827661221f0c4f092b\",\"name\":\"HitScoreVisualizer\",\"version\":\"2.2.0\",\"files\":[\"Plugins/HitScoreVisualizer.dll\"],\"dependsOn\":[\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe5b360a8c00640fb9709a\",\"name\":\"MappingExtensions\",\"version\":\"1.2.3\",\"files\":[\"Plugins/MappingExtensions.dll\"],\"dependsOn\":[\"Harmony\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d06db237661221f0c4f09f8\",\"name\":\"ParticleOverdrive\",\"version\":\"0.5.1\",\"files\":[\"Plugins/ParticleOverdrive.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d01b72c7661221f0c4f095c\",\"name\":\"PerfectionDisplay\",\"version\":\"1.6.1\",\"files\":[\"Plugins/PerfectDisplay.dll\"],\"dependsOn\":[\"CustomUI\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe9d99077a503d1075c553\",\"name\":\"SaberTailor\",\"version\":\"1.4.0\",\"files\":[\"Plugins/SaberTailor.dll\"],\"dependsOn\":[\"Harmony\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe572e0a8c00640fb9708b\",\"name\":\"PracticePlugin\",\"version\":\"4.4.0\",\"files\":[\"Plugins/PracticePlugin.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d085f57ed00193b6ebbab9f\",\"name\":\"CustomNotes\",\"version\":\"1.0.3\",\"files\":[\"CustomNotes/CatNote.bloq\",\"CustomNotes/Circle.bloq\",\"CustomNotes/DDRArrows.bloq\",\"CustomNotes/Minecraft.bloq\",\"CustomNotes/MusicEscape.bloq\",\"Plugins/CustomNotes.dll\"],\"dependsOn\":[\"CustomUI\",\"BSIPA\",\"BSUtils\",\"Harmony\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfeec667661221f0c4f08d9\",\"name\":\"Counters+\",\"version\":\"1.5.8\",\"files\":[\"Plugins/CountersPlus.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cfe9cfc077a503d1075c54f\",\"name\":\"SongRefreshButton\",\"version\":\"1.1.0\",\"files\":[\"Plugins/song-refresh-button.dll\"],\"dependsOn\":[\"SongCore\",\"CustomUI\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5cffcd177661221f0c4f0904\",\"name\":\"ScoreSaber\",\"version\":\"2.1.8\",\"files\":[\"Plugins/ScoreSaber.dll\"],\"dependsOn\":[\"Harmony\"],\"active\":true,\"dependencyOf\":[\"\"]},{\"id\":\"5cfeb1437661221f0c4f08b5\",\"name\":\"YURFitCalorieTracker\",\"version\":\"0.3.6\",\"files\":[\"BeatSaber_Data/Managed/YUR.dll\",\"BeatSaber_Data/Plugins/discord-rpc.dll\",\"Plugins/YURfit.dll\"],\"dependsOn\":[\"CustomUI\",\"BSUtils\",\"BSIPA\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d0425347661221f0c4f09b7\",\"name\":\"SongBrowser\",\"version\":\"5.0.0\",\"files\":[\"Plugins/SongBrowser.dll\"],\"dependsOn\":[\"SongCore\"],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5ca805de98ef0e6a459f47d6\",\"name\":\"BSIPA\",\"version\":\"3.12.6\",\"files\":[\"IPA/Data/Managed/I18N.dll\",\"IPA/Data/Managed/I18N.West.dll\",\"IPA/Data/Managed/IPA.Injector.dll\",\"IPA/Data/Managed/IPA.Injector.pdb\",\"IPA/Data/Managed/IPÜd|ÿ§A.Loader.dll\",\"IPA/Data/Managed/IPA.Loader.pdb\",\"IPA/Data/Managed/IPA.Loader.xml\",\"IPA/Data/Managed/System.Runtime.Serialization.dll\",\"IPA/Libs/0Harmony.1.2.0.1.dll\",\"IPA/Libs/Ionic.Zip.1.9.1.8.dll\",\"IPA/Libs/Mono.Cecil.0.10.3.0.dll\",\"IPA/Libs/Mono.Cecil.Mdb.0.10.3.0.dll\",\"IPA/Libs/Mono.Cecil.Pdb.0.10.3.0.dll\",\"IPA/Libs/Mono.Cecil.Rocks.0.10.3.0.dll\",\"IPA/Libs/Newtonsoft.Json.12.0.0.0.dll\",\"IPA/Libs/Newtonsoft.Json.12.0.0.0.pdb\",\"IPA/Libs/SemVer.1.2.0.0.dll\",\"IPA/winhttp.dll\",\"IPA.exe\",\"IPA.exe.config\"],\"dependsOn\":[],\"active\":true,\"dependencyOf\":[\"SongCore\",\"BSIPAModList\"]},{\"id\":\"5cda09e1d98de936054816c3\",\"name\":\"Microsoft.CSharp\",\"version\":\"4.6.57-Unity2018.2.14f1\",\"files\":[\"BeatSaber_Data/Managed/Microsoft.CSharp.dll\"],\"dependsOn\":[],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5ca577e2723eb30bd7190103\",\"name\":\"NewtonSoftJSON\",\"version\":\"12.0.1\",\"files\":[\"BeatSaber_Data/Managed/Newtonsoft.Json.dll\",\"BeatSaber_Data/Managed/System.Runtime.Serialization.dll\"],\"dependsOn\":[],\"active\":true,\"dependencyOf\":[]},{\"id\":\"5d0a6262ed00193b6ebbabb3\",\"name\":\"SongCore\",\"version\":\"2.0.10\",\"files\":[\"BeatSaber_Data/CustomLevels/OneMoreTime/cover.jpg\",\"BeatSaber_Data/CustomLevels/OneMoreTime/Credits.txt\",\"BeatSaber_Data/CustomLevels/OneMoreTime/Easy.dat\",\"BeatSaber_Data/CustomLevels/OneMoreTime/Expert.dat\",\"BeatSaber_Data/CustomLevels/OneMoreTime/Hard.dat\",\"BeatSaber_Data/CustomLevels/OneMoreTime/info.dat\",\"BeatSaber_Data/CustomLevels/OneMoreTime/lyrics.srt\",\"BeatSaber_Data/CustomLevels/OneMoreTime/Normal.dat\",\"BeatSaber_Data/CustomLevels/OneMoreTime/OneMoreTime.ogg\",\"Plugins/SongCore.dll\",\"songe-converter.exe\"],\"dependsOn\":[\"BSUtils\",\"BSIPA\",\"CustomUI\",\"Harmony\"],\"active\":true,\"dependencyOf\":[\"\"]},{\"id\":\"5d02e9fb7661221f0c4f0991\",\"name\":\"BSIPAModList\",\"version\":\"1.2.5\",\"files\":[\"Libs/CommonMark.0.1.0.0.dll\",\"Libs/CommonMark.0.1.0.0.pdb\",\"Plugins/BSIPA-ModList.dll\",\"Plugins/BSIPA-ModList.pdb\"],\"dependsOn\":[\"BSIPA\",\"CustomUI\"],\"active\":true,\"dependencyOf\":[]}],\"pendingInstall\":[\"SongLoader\"],\"scanning\":false,\"patching\":false}","playlists":"{\"playlists\":[],\"playlistDetails\":{\"playlistTitle\":\"\",\"playlistAuthor\":\"\",\"playlistDescription\":\"\",\"image\":\"\",\"songs\":[]},\"newCoverImageSource\":\"\",\"newPlaylistDialogOpen\":false,\"pickerOpen\":false,\"editing\":false}","details":"{\"isOpen\":false,\"loading\":false}","sidebar":"{\"isOpen\":true,\"section\":\"SONGS\"}","window":"{\"isMaximized\":false,\"isTranslucent\":true}","resource":"\"BEATSAVER_TOP_DOWNLOADED_SONGS\"","view":"{\"previousView\":\"SONG_LIST\",\"view\":\"SONG_LIST\",\"subView\":\"list\"}","settings":"{\"isOpen\":false,\"installationDirectory\":\"F:\\\\Games\\\\SteamLibrary\\\\steamapps\\\\common\\\\BeatSaber\",\"installationType\":\"steam\",\"gameVersion\":\"1.1.0\",\"autoLoadMore\":true,\"offlineMode\":false,\"theme\":\"dark\",\"themeImagePath\":\"\",\"folderStructure\":\"keySongNameArtistName\",\"updateChannel\":\"beta\",\"latestReleaseNotes\":\"2.5.4-beta\"}","loading":"false","loadingMore":"false","queue":"{\"isOpen\":false,\"items\":[{\"utc\":1561083334368,\"hash\":\"7c7f38d467bb43fe11a142581e63e324622ecc71\",\"image\":\"www.beatsaver.com/cdn/32e/7c7f38d467bb43fe11a142581e63e324622ecc71.jpg\",\"title\":\"DaftPunk-HarderBetterFasterStronger\",\"artist\":\"runrockgame\",\"progress\":100}]}","warnings":"[]","search":"{\"searchResults\":{\"beatSaver\":[],\"library\":[]}}","_persist":"{\"version\":-1,\"rehydrated\":true}"}`

Hope that helps.

**Comment by StarGazer1258** [comment]
There isn't really any log files for BeatDrop atm. What you are looking at is actually what the persist library uses to rehydrate the state of the app when it's closed then relaunched.

After updating and resetting the app, is the problem solved?

**Comment by xbkingx** [comment]
Yup, 2.5.5 seems to work fine without deleting the cache and shows no errors after rescanning tracks. Thanks!

**Comment by roydejong** [comment]
This issue is still happening for me on `2.5.5-beta`, and I don't think I've ever seen it before. Not sure how to debug or provide any additional information - let me know I can help with that.

It makes the app effectively unusable for me right now, there seem to be hundreds of messages (one for each song at this point?):

![image](https://user-images.githubusercontent.com/6772638/59959561-5ad13a00-94ba-11e9-8014-e986fae3dba8.png)

It's also worth noting that the update dialog does not understand beta versions, and offers to "update" to an older mainline version.
